#pragma once


#include <Geode/Geode.hpp>
#include <Geode/modify/PlayerObject.hpp>

using namespace geode::prelude;

class $modify(REPlayerObject, PlayerObject) {

    void stopGroundParticles__();
    std::string buildShipFireTextureName__(ShipStreak type, float time);
    void updateStreak__(CCMotionStreak* streak, ShipStreak streakType, PlayerObject* player);
    void scaleForStreak__(ShipStreak type, float speed, float scale, float* outA, float* outB);

    static PlayerObject* create(int player, int ship, GJBaseGameLayer* gameLayer, cocos2d::CCLayer* layer, bool playLayer);
    void update(float dt);
    void setScaleX(float scale);
    void setScaleY(float scale);
    void setScale(float scale);
    void setPosition(cocos2d::CCPoint const& position);
    void setVisible(bool visible);
    void setRotation(float rotation);
    void setOpacity(unsigned char opacity);
    void setColor(cocos2d::ccColor3B const& color);
    void setFlipX(bool flipX);
    void setFlipY(bool flipY);
    void resetObject();
    cocos2d::CCPoint getRealPosition();
    OBB2D* getOrientedBox();
    void animationFinished(char const* key);
    void activateStreak();
    void addAllParticles();
    void addToTouchedRings_(RingObject* object);
    void addToYVelocity_(double yVelocity, int type);
    void animatePlatformerJump(float scale);
    void boostPlayer(float yVelocity);
    void bumpPlayer(float bumpMod, int objectType, bool noEffects, GameObject* object);
    bool buttonDown_(PlayerButton button);
    bool canStickToGround_();
    void checkSnapJumpToObject(GameObject* object);
    bool collidedWithObject_(float dt, GameObject* object);
    bool collidedWithObject(float dt, GameObject* object, cocos2d::CCRect rect, bool skipCheck);
    bool collidedWithObjectInternal(float dt, GameObject* object, cocos2d::CCRect rect, bool skipCheck);
    void collidedWithSlope_(float dt, GameObject* object, bool skipPre);
    void collidedWithSlopeInternal(float dt, GameObject* object, bool forced);
    float convertToClosestRotation(float rotation);
    void copyAttributes(PlayerObject* player);
    void createFadeOutDartStreak();
    void createRobot(int frame);
    void createSpider(int frame);
    void deactivateParticle_();
    void deactivateStreak_(bool stop);
    bool destroyFromHitHead_();
    void didHitHead();
    void disableCustomGlowColor_();
    void disablePlayerControls();
    void disableSwingFire();
    void doReversePlayer(bool reverse);
    void enableCustomGlowColor_(cocos2d::ccColor3B const& color);
    void enablePlayerControls();
    void exitPlatformerAnimateJump();
    void fadeOutStreak2(float duration);
    void flashPlayer_(float flashDuration, float flashDelay, cocos2d::ccColor3B mainColor, cocos2d::ccColor3B secondColor);
    void flipGravity(bool flip, bool noEffects);
    int flipMod_();
    void gameEventTriggered_(int gameEvent, int material);
    GameObjectType getActiveMode_();
    double getCurrentXVelocity_();
    float getModifiedSlopeYVel_();
    float getObjectRotation();
    float getOldPosition_(float dt);
    cocos2d::ccColor3B getSecondColor_();
    double getYVelocity_();
    void gravityDown_();
    void gravityUp_();
    void handlePlayerCommand_(int command);
    bool handleRotatedCollisionInternal(float dt, GameObject* object, cocos2d::CCRect rect, bool skipCheck, bool skipPre, bool slope);
    bool handleRotatedObjectCollision_(float dt, GameObject* object, cocos2d::CCRect rect, bool skipCheck);
    void handleRotatedSlopeCollision_(float dt, GameObject* object, bool skipPre);
    void hardFlipGravity_();
    void hitGround(GameObject* object, bool notFlipped);
    void hitGroundNoJump(GameObject* object, bool notFlipped);
    void incrementJumps();
    bool init(int player, int ship, GJBaseGameLayer* gameLayer, cocos2d::CCLayer* layer, bool playLayer);
    bool isBoostValid_(float yVelocity);
    bool isFlying_();
    bool isInBasicMode_();
    bool isInNormalMode_();
    bool isSafeFlip_(float flipTime);
    bool isSafeHeadTest_();
    bool isSafeMode_(float changeTime);
    bool isSafeSpiderFlip_(float flipTime);
    void levelFlipFinished();
    bool levelFlipping();
    void levelWillFlip();
    void limitDashRotation_(float& rotation);
    void loadFromCheckpoint(PlayerCheckpoint* object);
    void lockPlayer();
    void logValues_();
    void modeDidChange_();
    void performSlideCheck_();
    void placeStreakPoint();
    void playBumpEffect(int objectType, GameObject* player);
    void playBurstEffect_();
    void playCompleteEffect(bool noEffects, bool instant);
    void playDeathEffect();
    void playDynamicSpiderRun();
    void playerDestroyed(bool noEffects);
    bool playerIsFalling_(float yVelocity);
    bool playerIsFallingBugged();
    bool playerIsMovingUp_();
    void playerTeleported_();
    void playingEndEffect_();
    void playSpawnEffect();
    void playSpiderDashEffect(cocos2d::CCPoint from, cocos2d::CCPoint to);
    void postCollision(float dt, bool betweenSteps);
    void preCollision_();
    bool preSlopeCollision(float dt, GameObject* object);
    void propellPlayer(float yVelocity, bool noEffects, int objectType);
    bool pushButton(PlayerButton button);
    void pushDown_();
    void pushPlayer_(float yVelocity);
    void redirectDash_(float rotation);
    void redirectPlayerForce(float rotation, float modifier, float minimum, float maximum);
    void releaseAllButtons();
    bool releaseButton(PlayerButton button);
    void removeAllParticles_();
    void removePendingCheckpoint();
    void removePlacedCheckpoint_();
    void resetAllParticles();
    void resetCollisionLog_(bool full);
    void resetCollisionValues_();
    void resetPlayerIcon();
    void resetStateVariables_();
    void resetStreak();
    void resetTouchedRings(bool removeAll);
    int reverseMod_();
    void reversePlayer(EffectGameObject* object);
    void ringJump(RingObject* object, bool skipCheck);
    void rotateGameplay(int moveDirection, int groundDirection, bool editVelocity, float velocityModX, float velocityModY, bool overrideVelocity, bool dontSlide);
    void rotateGameplayObject(GameObject* object);
    void rotateGameplayOnly_(bool sideways);
    void rotatePreSlopeObjects_();
    void runBallRotation(float speed);
    void runBallRotation2();
    void runNormalRotation_();
    void runNormalRotation(bool notNormalMode, float speed);
    void runRotateAction_(bool ground, int type);
    void saveToCheckpoint(PlayerCheckpoint* checkpoint);
    void setSecondColor(cocos2d::ccColor3B const& color);
    void setupStreak();
    void setYVelocity(double velocity, int type);
    void spawnCircle();
    void spawnCircle2_();
    void spawnDualCircle();
    void spawnFromPlayer_(PlayerObject* player, bool flip);
    void spawnPortalCircle(cocos2d::ccColor3B color, float startRadius);
    void spawnScaleCircle();
    void specialGroundHit_();
    void speedDown_();
    void speedUp_();
    void spiderTestJump(bool dynamic);
    void spiderTestJumpInternal(bool dynamic);
    void spiderTestJumpX_(bool dynamic); // missing windows binding
    void spiderTestJumpY_(bool dynamic); // missing windows binding
    void startDashing(DashRingObject* object);
    void stopBurstEffect();
    void stopDashing();
    void stopParticles();
    void stopPlatformerJumpAnimation();
    void stopRotation_(bool ground, int type);
    void stopStreak2_();
    void storeCollision_(PlayerCollisionDirection direction, int id);
    bool switchedDirTo(PlayerButton button);
    void switchedToMode(GameObjectType type);
    bool testForMoving_(float dt, GameObject* object);
    void toggleBirdMode(bool enable, bool noEffects);
    void toggleDartMode(bool enable, bool noEffects);
    void toggleFlyMode(bool enable, bool noEffects);
    void toggleGhostEffect(GhostType type);
    void togglePlatformerMode_(bool val);
    void togglePlayerScale(bool enable, bool noEffects);
    void toggleRobotMode(bool enable, bool noEffects);
    void toggleRollMode(bool enable, bool noEffects);
    void toggleSpiderMode(bool enable, bool noEffects);
    void toggleSwingMode(bool enable, bool noEffects);
    void toggleVisibility(bool visible);
    void touchedObject_(GameObject* object);
    void tryPlaceCheckpoint();
    void unrotateGameplayObject(GameObject* object);
    void unrotatePreSlopeObjects_();
    void updateCheckpointMode_(bool enable);
    void updateCheckpointTest_();
    void updateCollide(PlayerCollisionDirection direction, GameObject* object);
    void updateCollideBottom_(float y, GameObject* object);
    void updateCollideLeft(float x, GameObject* object);
    void updateCollideRight(float x, GameObject* object);
    void updateCollideTop_(float y, GameObject* object);
    void updateDashAnimation();
    void updateDashArt();
    void updateEffects_(float param);
    void updateGlowColor();
    void updateInternalActions(float dt);
    void updateJump(float dt);
    void updateJumpVariables_();
    void updateLastGroundObject_(GameObject* object);
    void updateMove(float dt);
    void updatePlayerArt();
    void updatePlayerBirdFrame(int frame);
    void updatePlayerDartFrame(int frame);
    void updatePlayerForce_(cocos2d::CCPoint velocity, bool additive);
    void updatePlayerFrame(int frame);
    void updatePlayerGlow();
    void updatePlayerJetpackFrame(int frame);
    void updatePlayerRobotFrame_(int frame);
    void updatePlayerRollFrame(int frame);
    void updatePlayerScale();
    void updatePlayerShipFrame(int frame);
    void updatePlayerSpiderFrame_(int frame);
    void updatePlayerSpriteExtra(gd::string frameName);
    void updatePlayerSwingFrame(int frame);
    void updateRobotAnimationSpeed();
    void updateRotation(float dt);
    void updateRotation(float dt, float rotation);
    void updateShipRotation(float dt);
    void updateShipSpriteExtra(gd::string frameName);
    void updateSlopeRotation(float dt);
    void updateSlopeYVelocity_(float yVelocity);
    void updateSpecial_(float dt);
    void updateStateVariables_();
    void updateStaticForce_(float rotation, float staticForce, bool additive);
    void updateStreakBlend(bool blend);
    void updateStreaks_(float dt);
    void updateSwingFire();
    void updateTimeMod(float speed, bool noEffects);
    bool usingWallLimitedMode_();
    void yStartDown_();
    void yStartUp_();

};